import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import Image from "next/image";
import coverImg from "/public/images/bg5.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: "100vh" }}>
        <div className="absolute inset-0">
          <Image
            src={coverImg}
            alt="Background"
            layout="fill"
            objectFit="cover"
            style={{ opacity: 0.4, zIndex: 0 }}
            priority
          />
        </div>
        <AuthProvider>
          <div className="relative">
            <Navbar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
